### ISSUE TITLE
on_expired_session not fired when zookeeper server stop

### ISSUE THREAD

**Issue by tomwang1013** [zk-ruby/zk#91]
i use `zk.on_expired_session` wishing to be notified when it can not connect to the server. But when i stop the zk server, no `session_expired` event is received. Instead, `ZOO_CONNECTING_STATE` was received. 
As i read the doc, `connecting` means `the client is attempting to reconnect to the zookeeper server`. So why `session_expired` is missing?

**Comment by slyphon** [comment]
The on_expired_session refers to a specific condition in this [state diagram](https://zookeeper.apache.org/doc/r3.4.7/zookeeperProgrammers.html):

![zk-state](https://zookeeper.apache.org/doc/r3.4.7/images/state_dia.jpg)

> A ZooKeeper client establishes a session with the ZooKeeper service by creating a handle to the service using a language binding. Once created, the handle starts of in the CONNECTING state and the client library tries to connect to one of the servers that make up the ZooKeeper service at which point it switches to the CONNECTED state. During normal operation will be in one of these two states. If an unrecoverable error occurs, such as session expiration or authentication failure, or if the application explicitly closes the handle, the handle will move to the CLOSED state. 

> When a client (session) becomes partitioned from the ZK serving cluster it will begin searching the list of servers that were specified during session creation. Eventually, when connectivity between the client and at least one of the servers is re-established, the session will either again transition to the "connected" state (if reconnected within the session timeout value) or it will transition to the "expired" state (if reconnected after the session timeout).

This callback is _very_ rare to actually see in practice (I've never been able to force it to happen in testing). It's a specific state that can happen on reconnect, but rarely does.
